export const selector = {
    src : "http://localhost:8181/secure/project/DeleteProject!default.jspa?pid=10629&pcp=true",
    frame : "http://localhost:8181/secure/project/BrowseProjects.jspa?s=view_projects",

    usernameInput : 'Username*',
    passwordInput : 'password-input',
    loginButton : 'login-button',
    button : 'button',
    projects : 'Projects',
    createProject : 'Create project',
    link : 'link',
    next : 'Next',
    select : 'Select',
    name : 'Name',
    submit : 'Submit',
    create :  'Create',
    task : 'Task',
    story : 'Story',
    bug : 'Bug',

    //issue cards
    epicFill : "//input[@id='customfield_10102']",
    epicName : 'Epic Name Required',
    summaryReq : 'Summary Required',
    paragraph : 'paragraph',
    description : 'iframe[title="Rich Text Area"]',
    des : "//iframe[@id='mce_7_ifr']",
    richTextArea : 'Description, Rich Text Area.',
    combox : 'combobox',
    labels : 'Labels',
    option : 'option',
    priority : 'Priority',
    dashboard : 'dashboard (New Label)',
    createAnother : 'Create another',
    submitButton : 'Press Ctrl+Alt+s to submit',
    analytics : 'Analytics (New Label)',
    issueTypeReq : 'Issue Type Required',
    epic1 : 'EPIC-001 - (PROJ-1)',
    epic2 : 'EPIC-002 - (PROJ-2)',
    epicLink : 'Epic Link',
    assignTo : 'Assign to me',
    issueLink : "//select[@id='issuelinks-linktype']",
    issueTag : "//label[@for='issuelinks-issues-textarea']",
    
    //priority
    high : 'High',
    highest : 'Highest',
    med : 'Medium',
    low : 'Low',
    lowest : 'Lowest'
}